#!/usr/bin/env python3
import json,subprocess
from pathlib import Path
R=Path(__file__).resolve().parents[1];A="0.5.122";B="0.5.123"
def p(n):return R/n
def rd(n):return p(n).read_text(encoding="utf-8")
def wr(n,s):p(n).write_text(s,encoding="utf-8")
def rp(n,a,b):
 s=rd(n)
 if s.count(a)!=1:raise RuntimeError(f"{n}: anchor count {s.count(a)}")
 wr(n,s.replace(a,b,1))
def ap(n,m,b):
 s=rd(n)
 if m not in s:wr(n,s.rstrip()+"\n\n"+b.rstrip()+"\n")
H='  function setIntegrationHealth(card,tone=\'unknown\',message=\'Not checked\'){\n    const el=card?.querySelector(\'[data-integration-health]\');if(!el)return;\n    const icon=tone===\'healthy\'?\'check_circle\':tone===\'degraded\'?\'warning\':tone===\'offline\'?\'error\':\'remove_circle\';\n    el.className=`integration-health ${tone}`;el.innerHTML=materialIconSvg(icon);el.title=message;el.setAttribute(\'aria-label\',`Integration status: ${message}`);card.dataset.health=tone;\n  }\n  async function checkIntegrationHealth(card){\n    if(!card?.dataset.id)return;\n    const saved=integrations.find(x=>String(x.id||\'\')===card.dataset.id);\n    if(!saved||saved.enabled===false)return setIntegrationHealth(card,\'disabled\',\'Disabled\');\n    if(!PASSIVE_INTEGRATION_HEALTH_TYPES.has(card.dataset.type))return setIntegrationHealth(card,\'unknown\',\'Status available after Test connection\');\n    if(card.dataset.healthLoading===\'1\')return;card.dataset.healthLoading=\'1\';\n    try{\n      if(card.dataset.type===\'jellyfin\'){\n        const data=await api(`/api/integrations/jellyfin/status?id=${encodeURIComponent(card.dataset.id)}`);\n        setIntegrationHealth(card,data?.server?.pending_restart?\'degraded\':\'healthy\',data?.server?.pending_restart?\'Connected · Restart pending\':\'Connected\');\n      }else{const data=await post(\'/api/integration-test\',saved);setIntegrationHealth(card,\'healthy\',data.message||\'Connected\')}\n    }catch(e){setIntegrationHealth(card,\'offline\',e.message||\'Could not connect\')}finally{delete card.dataset.healthLoading}\n  }\n  function refreshIntegrationHealth(force=false){\n    const page=document.querySelector(\'[data-settings-section="integrations"]\');if(!force&&!page?.classList.contains(\'active\'))return;\n    document.querySelectorAll(\'.integration-item\').forEach(checkIntegrationHealth);\n    if(!integrationHealthTimer)integrationHealthTimer=setInterval(()=>refreshIntegrationHealth(false),INTEGRATION_HEALTH_REFRESH_MS);\n  }\n\n'
CSS='/* 0.5.123 integration health indicators */\n.integration-summary-title{display:flex;align-items:center;gap:7px;min-width:0}.integration-summary-title b{min-width:0}\n.integration-health{display:inline-flex;align-items:center;justify-content:center;flex:0 0 18px;width:18px;height:18px}.integration-health .material-symbol-icon{width:17px;height:17px}\n.integration-health.healthy{color:#43c978}.integration-health.degraded{color:#e6b64b}.integration-health.offline{color:#ef646d}.integration-health.disabled,.integration-health.unknown{color:var(--muted);opacity:.72}\n'
DOC='## Integration health indicators\n\nSaved integrations show a Material status glyph before the name: green is healthy, yellow is reachable but degraded, red is unreachable, and muted gray is disabled or not passively checked. Background health polling must never emit notification/webhook test messages. Jellyfin treats a pending restart as degraded; Sonarr, Radarr, Lidarr, Prowlarr, and Plex use their passive connection checks. The built-in completion sound is the locally shipped maintainer-selected MP3; custom sounds still override it.\n'
TST='### Integration health indicators and default sound\n\n- Verify every saved integration has a status icon immediately before its name.\n- Verify Jellyfin is green normally, yellow for `HasPendingRestart`, and red when unreachable.\n- Verify Sonarr/Radarr/Lidarr/Prowlarr/Plex become green/red from passive checks while Integrations is active.\n- Verify disabled integrations are gray. Discord, ntfy, Generic webhook, and Home Assistant must remain gray until explicit Test connection and must never emit messages from background polling.\n- Verify Test connection updates the icon green/red.\n- Enable Default completion sound, run Test notification, and complete a torrent; both must play the shipped MP3. Custom sound behavior remains unchanged.\n'
V='    # 0.5.123 integration health indicators and default completion sound.\n    assert "const PASSIVE_INTEGRATION_HEALTH_TYPES=new Set([\'sonarr\',\'radarr\',\'lidarr\',\'prowlarr\',\'jellyfin\',\'plex\']);" in settings_js\n    assert \'const INTEGRATION_HEALTH_REFRESH_MS=60000;\' in settings_js\n    assert \'function setIntegrationHealth\' in settings_js and \'function refreshIntegrationHealth\' in settings_js\n    assert \'data-integration-health\' in settings_js and "materialIconSvg(\'remove_circle\')" in settings_js\n    assert "data?.server?.pending_restart?\'degraded\':\'healthy\'" in settings_js\n    assert \'0.5.123 integration health indicators\' in settings_css\n    assert \'/static/default-completion.wav\' not in app_js and \'/static/default-completion.wav\' not in settings_js\n    assert \'/static/default-completion.mp3\' in app_js and \'/static/default-completion.mp3\' in settings_js\n    sound=ROOT/\'static\'/\'default-completion.mp3\';assert sound.is_file() and hashlib.sha256(sound.read_bytes()).hexdigest()==\'59f44c09464a2e3956e5f9ecf5bca711c518baf38995006554b7f5ea7d1321eb\'\n    assert not (ROOT/\'static\'/\'default-completion.wav\').exists()\n    assert "\'/static/default-completion.mp3?v=0.5.123\'" in (ROOT/\'static\'/\'sw.js\').read_text(encoding=\'utf-8\')\n    assert \'## Integration health indicators\' in design_language and \'### Integration health indicators and default sound\' in testing_md\n\n'

rp("dashboard.py",'VERSION = "0.5.122"','VERSION = "0.5.123"')
for n in ("static/index.html","static/app.js","static/sw.js"):wr(n,rd(n).replace(A,B))
for n in ("static/app.js","static/settings.js"):
 s=rd(n)
 if "/static/default-completion.wav" not in s:raise RuntimeError("old sound ref missing")
 wr(n,s.replace("/static/default-completion.wav","/static/default-completion.mp3"))
if not p("static/default-completion.mp3").is_file():raise RuntimeError("MP3 missing")
p("static/default-completion.wav").unlink(missing_ok=True)
s=rd("static/sw.js");x="'/static/default-completion.mp3?v=0.5.123'"
if x not in s:s=s.replace("'/static/favicon.svg']",f"'/static/favicon.svg',{x}]")
wr("static/sw.js",s)
rp("static/app.js","  notifications:'M12 22c1.1 0 1.99-.9 1.99-2h-4A2 2 0 0 0 12 22Zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4a1.5 1.5 0 0 0-3 0v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2Z',\n","  notifications:'M12 22c1.1 0 1.99-.9 1.99-2h-4A2 2 0 0 0 12 22Zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4a1.5 1.5 0 0 0-3 0v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2Z',\n  check_circle:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm-2 15-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9Z',\n  warning:'M1 21h22L12 2 1 21Zm12-3h-2v-2h2v2Zm0-4h-2v-4h2v4Z',\n  error:'M12 2a10 10 0 1 0 .001 20.001A10 10 0 0 0 12 2Zm1 15h-2v-2h2v2Zm0-4h-2V7h2v6Z',\n  remove_circle:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm5 11H7v-2h10v2Z',\n")
rp("static/settings.js","  let clientSettingsServerId = '';\n\n  const corePages","  let clientSettingsServerId = '';\n  const PASSIVE_INTEGRATION_HEALTH_TYPES=new Set(['sonarr','radarr','lidarr','prowlarr','jellyfin','plex']);\n  const INTEGRATION_HEALTH_REFRESH_MS=60000;\n  let integrationHealthTimer=null;\n\n  const corePages")
rp("static/settings.js","    if (savebar) savebar.classList.toggle('hidden', !corePages.has(page));\n","    if (savebar) savebar.classList.toggle('hidden', !corePages.has(page));\n    if(page==='integrations')setTimeout(()=>refreshIntegrationHealth(true),0);\n")
rp("static/settings.js","  function jellyfinServiceMarkup(item) {\n",H+"  function jellyfinServiceMarkup(item) {\n")
rp("static/settings.js","      runtime.dataset.loaded='1';renderJellyfinOverview(card,data);\n","      runtime.dataset.loaded='1';renderJellyfinOverview(card,data);\n      setIntegrationHealth(card,data?.server?.pending_restart?'degraded':'healthy',data?.server?.pending_restart?'Connected · Restart pending':'Connected');\n")
rp("static/settings.js","    }catch(error){\n      if(status){status.className='service-status-badge offline';status.textContent='Offline'}\n","    }catch(error){\n      setIntegrationHealth(card,'offline',error.message||'Could not connect');\n      if(status){status.className='service-status-badge offline';status.textContent='Offline'}\n")
old='card.innerHTML = `<button class="accordion-summary" type="button" aria-expanded="${index===0?\'true\':\'false\'}"><span><b>${esc(integrationLabel(item))}</b>${subtitle?`<small>${esc(subtitle)}</small>`:\'\'}'
new='card.innerHTML = `<button class="accordion-summary" type="button" aria-expanded="${index===0?\'true\':\'false\'}"><span><span class="integration-summary-title"><span class="integration-health ${item.enabled===false?\'disabled\':\'unknown\'}" data-integration-health title="${item.enabled===false?\'Disabled\':\'Not checked\'}" aria-label="Integration status: ${item.enabled===false?\'Disabled\':\'Not checked\'}">${materialIconSvg(\'remove_circle\')}</span><b>${esc(integrationLabel(item))}</b></span>${subtitle?`<small>${esc(subtitle)}</small>`:\'\'}'
rp("static/settings.js",old,new)
rp("static/settings.js","      if(index===0&&card.dataset.type==='jellyfin'&&card.dataset.id)setTimeout(()=>loadJellyfinOverview(card),0);\n","      if(item.enabled===false)setIntegrationHealth(card,'disabled','Disabled');\n      if(document.querySelector('[data-settings-section=\"integrations\"]')?.classList.contains('active')&&card.dataset.id)setTimeout(()=>checkIntegrationHealth(card),0);\n")
rp("static/settings.js","      out.className='test-result ok integration-result';\n      out.textContent=d.message || 'Connected';\n","      out.className='test-result ok integration-result';\n      out.textContent=d.message || 'Connected';\n      setIntegrationHealth(card,'healthy',d.message||'Connected');\n      if(card.dataset.type==='jellyfin'&&card.dataset.id)await loadJellyfinOverview(card);\n")
rp("static/settings.js","      out.className='test-result bad integration-result';\n      out.textContent=e.message;\n","      out.className='test-result bad integration-result';\n      out.textContent=e.message;\n      setIntegrationHealth(card,'offline',e.message||'Could not connect');\n")
ap("static/settings.css","0.5.123 integration health indicators",CSS)
ap("DESIGN_LANGUAGE.md","## Integration health indicators",DOC)
ap("TESTING.md","### Integration health indicators and default sound",TST)
v=rd("release_tools/validate_ui_strings.py")
if "import hashlib\n" not in v:v=v.replace("import re\n","import hashlib\nimport re\n",1)
if "0.5.123 integration health indicators and default completion sound" not in v:v=v.replace('    print("UI string audit passed")',V+'    print("UI string audit passed")')
wr("release_tools/validate_ui_strings.py",v)
m=json.loads(rd("release_notes/releases.json"))
if not any(x.get("version")==B for x in m["releases"]):
 q=next(x for x in reversed(m["releases"]) if x.get("version")==A);d=list(q.get("decisions") or [])
 d+=["Background integration health checks must be side-effect-free; notification destinations are only tested on explicit user action.","Use the maintainer-selected local MP3 as the built-in completion sound while preserving custom sound overrides."]
 m["releases"].append({"version":B,"date":"2026-09-06","status":"prerelease","title":"Integration health indicators and notification sound","summary":"Adds at-a-glance integration health states and makes the maintainer-selected notification tone the built-in default.","highlights":["Saved integrations show green healthy, yellow degraded, red unavailable, or gray disabled/not-checked Material status indicators.","Jellyfin uses live status including restart-pending degradation; Sonarr, Radarr, Lidarr, Prowlarr, and Plex are checked passively while Integrations is active.","The uploaded notification tone replaces the old built-in WAV as the local default completion sound."],"fixes":["Integration health is visible without opening and manually testing each service.","Default sound mode now uses the requested replacement notification tone."],"technical":["Passive health polling runs every 60 seconds only while Integrations is active; notification/webhook destinations are never background-tested because their tests emit messages.","The default completion asset is now MP3 and is cached by the service worker."],"validation":["The UI audit requires health-state markup/polling, the exact MP3 digest, WAV removal, service-worker inclusion, and documentation.","Existing backend, JavaScript, generated-state, and prerelease package-integrity gates remain required."],"known_issues":["Notification-only integrations return to gray after page reload until Test connection is explicitly run."],"architecture":list(q.get("architecture") or []),"decisions":d,"next_steps":list(q.get("next_steps") or [])})
wr("release_notes/releases.json",json.dumps(m,indent=2)+"\n")
for q in p("release_tools").glob("notification_sound_chunk_*.txt"):q.unlink()
subprocess.run(["python","release_tools/generate_release_notes.py","--version",B],cwd=R,check=True)
