#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, text: str) -> None:
    (ROOT / path).write_text(text, encoding="utf-8")


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected exactly one match, found {count}")
    return text.replace(old, new, 1)


# Version and cache-busting.
dashboard = read("dashboard.py")
dashboard = replace_once(dashboard, 'VERSION = "0.5.32"', 'VERSION = "0.5.33"', "version")
write("dashboard.py", dashboard)

html = read("static/index.html")
html = html.replace("?v=0.5.32", "?v=0.5.33")
html_replacements = [
    ('id="wRefreshInterfaces" type="button">Refresh Interfaces</button>', 'id="wRefreshInterfaces" type="button">Refresh</button>', "setup interface refresh"),
    ('id="wTestClient" type="button">Test qBitTorrent Connection</button>', 'id="wTestClient" type="button">Test connection</button>', "setup client test"),
    ('<div class="test-result muted" id="wClientResult">Not Tested Yet</div>', '<div class="test-result muted" id="wClientResult"></div>', "setup test status"),
    ('<h1>Torrent Dashboard</h1><p>Sign In To Dashboard</p>', '<h1>Torrent Dashboard</h1><p>Sign in</p>', "login subtitle"),
    ('<div class="empty hidden" id="empty"><strong>No Torrents Match This View</strong><span>Change the filter or search query.</span></div>', '<div class="empty hidden" id="empty"><strong>No matching torrents</strong><span>Change the filter or search query.</span></div>', "torrent empty state"),
    ('<div class="notification-toolbar"><div><strong>Recent activity</strong><span>Torrent completions, account activity, updates, integrations, and dashboard events.</span></div>', '<div class="notification-toolbar"><div><strong>Recent activity</strong><span>Torrent, account, update, integration, and system events.</span></div>', "notification center subtitle"),
    ('<label>Dashboard Title<input id="sTitle"/></label>', '<label>Dashboard Name<input id="sTitle"/></label>', "dashboard name label"),
    ('<div class="field-help">Usernames, passwords, profile information, and access roles are managed under User Management.</div>', '<div class="field-help">Usernames, passwords, profiles, and roles are managed under Users.</div>', "access users helper"),
    ('id="sRefreshInterfaces" type="button">Refresh Interfaces</button>', 'id="sRefreshInterfaces" type="button">Refresh</button>', "settings interface refresh"),
    ('id="copyLocalAddress" type="button">Copy Address</button>', 'id="copyLocalAddress" type="button">Copy</button>', "copy address"),
    ('<p class="muted client-settings-intro">Manage each download client connection here. Use Settings on a saved client for its live qBitTorrent transfer preferences.</p>', '<p class="muted client-settings-intro">Manage client connections here. Use Settings for qBitTorrent speed, connection, and proxy options.</p>', "clients intro"),
    ('<button id="addServerSetting" type="button">＋ Add Server</button>', '<button id="addServerSetting" type="button">＋ Add Client</button>', "add client"),
    ("Public GitHub repository used as this dashboard's update source. Save changes before checking for updates; Check for updates validates the repository before comparing releases.", 'Public GitHub repository used for updates. Save changes before checking.', "updates helper"),
    ('<div class="muted update-message" id="updateMessage">Check the configured public repository for a newer Torrent Dashboard release.</div>', '<div class="muted update-message" id="updateMessage">Check for a newer Torrent Dashboard release.</div>', "updates initial message"),
    ('<p class="muted notification-intro">Configure notifications generated by this browser. External delivery services such as Discord, ntfy, and webhooks are managed under Integrations.</p>', '<p class="muted notification-intro">Configure browser and completion notifications. Discord, ntfy, and webhooks are under Integrations.</p>', "notifications intro"),
    ('<div class="field-help">Uses the browser and operating system notification permission for completion alerts.</div>', '<div class="field-help">Requires browser notification permission.</div>', "browser notification helper"),
    ('<div class="configured-sound" id="nCustomSoundName">No Custom Sound Uploaded</div>', '<div class="configured-sound" id="nCustomSoundName">None uploaded</div>', "custom sound empty"),
    ('<div class="field-help">WAV, MP3, or OGG · Maximum 2 MB. Custom sounds are stored in the data directory and preserved during updates.</div>', '<div class="field-help">WAV, MP3, or OGG · 2 MB max · Preserved during updates.</div>', "custom sound helper"),
    ('id="testNotification" type="button">Test Notification</button>', 'id="testNotification" type="button">Test</button>', "notification test button"),
    ('<div class="test-result muted" id="soundStatus">Test browser notifications and completion audio. Browser permission is requested during the test when needed.</div>', '<div class="test-result muted" id="soundStatus"></div>', "notification status"),
    ('<div class="panel settings-card"><div class="panel-title">Integrations</div><p class="muted">No integrations are populated by default. Add media services or notification destinations only when you use them, test each connection, and save it independently.</p>', '<div class="panel settings-card"><div class="panel-title">Integrations</div><p class="muted">Add media services and notification destinations. Each integration is tested and saved independently.</p>', "integrations intro"),
    ('<div class="panel settings-card"><div class="panel-title">Users</div><p class="muted user-management-intro">Administrators can manage torrents, settings, integrations, and users. Standard Users can manage their own account and profile while dashboard management remains read-only.</p>', '<div class="panel settings-card"><div class="panel-title">Users</div><p class="muted user-management-intro">Administrators manage the dashboard. Standard Users have read-only dashboard access and can manage their own account.</p>', "users intro"),
    ('<div class="drawer hidden" id="drawer"><div class="drawer-backdrop" data-close=""></div><section class="drawer-sheet"><header><div><h2 id="detailName">Torrent</h2><p id="detailMeta">—</p></div><button class="icon-btn" data-close="">×</button>', '<div class="drawer hidden" id="drawer"><div class="drawer-backdrop" data-close=""></div><section class="drawer-sheet"><header><div><h2 id="detailName">Torrent</h2><p id="detailMeta">—</p></div><button class="icon-btn" data-close="" type="button" aria-label="Close details">×</button>', "drawer close accessibility"),
    ('<div class="modal hidden" id="addModal"><div class="modal-backdrop" data-modalclose=""></div><form class="modal-card" id="addForm"><header><h2>Add Torrent</h2><button class="icon-btn" data-modalclose="" type="button">×</button>', '<div class="modal hidden" id="addModal"><div class="modal-backdrop" data-modalclose=""></div><form class="modal-card" id="addForm"><header><h2>Add Torrent</h2><button class="icon-btn" data-modalclose="" type="button" aria-label="Close add torrent">×</button>', "add torrent close accessibility"),
    ('<form class="modal-card remove-modal-card" id="removeForm"><header><div><h2>Remove torrent(s)</h2><p>Remove torrents from qBitTorrent.</p></div>', '<form class="modal-card remove-modal-card" id="removeForm"><header><div><h2 id="removeModalTitle">Remove torrent</h2></div>', "remove modal title"),
    ('<strong id="removePrompt">Are you sure you want to remove this torrent from the transfer list?</strong><p>This action removes the selected torrent from qBitTorrent. Downloaded files are kept unless you choose otherwise below.</p>', '<strong id="removePrompt">Remove this torrent from qBitTorrent?</strong><p>Downloaded files are kept unless you choose to delete them below.</p>', "remove modal copy"),
    ('<h2 id="accountModalTitle">Account settings</h2><p>Manage your personal Torrent Dashboard account.</p>', '<h2 id="accountModalTitle">Account settings</h2><p>Manage your profile and password.</p>', "account subtitle"),
    ('<strong>Profile picture</strong><p>PNG, JPG, or WebP · Maximum 4 MB.</p>', '<strong>Profile picture</strong><p>PNG, JPG, or WebP · 4 MB max.</p>', "avatar helper"),
    ('<div class="field-help">Changing your password requires confirmation in a separate prompt and a new password of at least 8 characters.</div>', '<div class="field-help">Minimum 8 characters. Your current password is confirmed before saving.</div>', "password helper"),
    ('<p id="passwordConfirmMessage">Enter your current password to continue with this secure account change.</p>', '<p id="passwordConfirmMessage">Enter your current password to continue.</p>', "password confirmation copy"),
    ("<div class=\"client-settings-section-heading\"><strong>Proxy</strong><span>Configure qBitTorrent's outbound proxy without exposing stored proxy passwords to Torrent Dashboard clients.</span></div>", "<div class=\"client-settings-section-heading\"><strong>Proxy</strong><span>Configure qBitTorrent's outbound proxy.</span></div>", "proxy helper"),
]
for old, new, label in html_replacements:
    html = replace_once(html, old, new, label)
write("static/index.html", html)

# Main application copy, status handling, and dialog consistency.
app_js = read("static/app.js")
app_replacements = [
    ("<div class=\"interface-empty\"><b>No Network Interfaces Detected</b><span>You can still use the IP address whitelist below.</span></div>", "<div class=\"interface-empty\"><b>No network interfaces</b><span>You can still use the IP address whitelist below.</span></div>", "interface empty state"),
    ("$('#wClientResult').textContent='Not Tested Yet'", "$('#wClientResult').textContent=''", "wizard test reset"),
    ("out.className='test-result muted';out.textContent=uiText('testing…')", "out.className='test-result muted';out.textContent='Testing…'", "setup test progress"),
    ("btn.textContent='Testing And Saving…'", "btn.textContent='Finishing…'", "setup finish progress"),
    ("err.message||'Setup Could Not Be Completed'", "err.message||'Setup failed.'", "setup fallback error"),
    ("out.textContent=uiText('testing…');out.className='server-test-result'", "out.textContent='Testing…';out.className='server-test-result'", "client test progress"),
    ("copy.textContent=message||'Enter your current password to continue with this secure account change.'", "copy.textContent=message||'Enter your current password to continue.'", "password confirmation default"),
    ("requestPasswordConfirmation('Confirm your current password to change your username or email address.')", "requestPasswordConfirmation('Confirm your password to change your username or email.')", "profile confirmation"),
    ("requestPasswordConfirmation('Confirm your current password to change your password.')", "requestPasswordConfirmation('Confirm your password to change it.')", "password change confirmation"),
    ("applyAccountUser(d.user);accountProfileSnapshot={...d.user};status.className='test-result ok';status.textContent='Profile saved.';toast('profileSaved');", "applyAccountUser(d.user);accountProfileSnapshot={...d.user};status.className='test-result ok';status.textContent='Profile saved.';", "profile duplicate feedback"),
    ("$('#accountPasswordForm').reset();status.className='test-result ok';status.textContent='Password changed.';toast('passwordChanged');", "$('#accountPasswordForm').reset();status.className='test-result ok';status.textContent='Password changed.';", "password duplicate feedback"),
    ("const d=await api('/api/account/avatar',{method:'POST',body:form});applyAccountUser(d.user);status.className='test-result ok';status.textContent='Profile picture updated.';toast('profilePictureUpdated');", "const d=await api('/api/account/avatar',{method:'POST',body:form});applyAccountUser(d.user);status.className='test-result ok';status.textContent='Profile picture updated.';", "avatar duplicate feedback"),
    ("try{const d=await post('/api/account/avatar/delete',{});applyAccountUser(d.user);status.className='test-result ok';status.textContent='Profile picture removed.';toast('profilePictureRemoved')}catch(e)", "try{const d=await post('/api/account/avatar/delete',{});applyAccountUser(d.user);status.className='test-result ok';status.textContent='Profile picture removed.'}catch(e)", "avatar removal duplicate feedback"),
]
for old, new, label in app_replacements:
    app_js = replace_once(app_js, old, new, label)
old_remove = "const one=targets.length===1;const name=targets[0]?.name||targets[0]?.hash||'this torrent';$('#removePrompt').textContent=one?`Are you sure you want to remove “${name}” from the transfer list?`:`Are you sure you want to remove ${targets.length} torrents from the transfer list?`;"
new_remove = "const one=targets.length===1;const name=targets[0]?.name||targets[0]?.hash||'this torrent';$('#removeModalTitle').textContent=one?'Remove torrent':'Remove torrents';$('#removePrompt').textContent=one?`Remove “${name}” from qBitTorrent?`:`Remove ${targets.length} torrents from qBitTorrent?`;"
app_js = replace_once(app_js, old_remove, new_remove, "remove dialog runtime copy")
write("static/app.js", app_js)

# Settings copy, concise statuses, and custom deletion confirmations.
settings_js = read("static/settings.js")
settings_replacements = [
    ("return toast('Save The Client Before Opening Client Settings','error')", "return toast('Save the client before opening Settings.','error')", "unsaved client settings"),
    ("setClientSettingsStatus('Loading client settings…')", "setClientSettingsStatus('Loading…')", "client settings loading"),
    ("setClientSettingsStatus('Live settings loaded from qBitTorrent.')", "setClientSettingsStatus('')", "client settings loaded"),
    ("e.message || 'Could not load client settings.'", "e.message || 'Could not load settings.'", "client settings load error"),
    ("setClientSettingsStatus('Enter valid whole numbers for the client limits and ports.', 'bad')", "setClientSettingsStatus('Enter whole numbers for limits and ports.', 'bad')", "client numeric error"),
    ("setClientSettingsStatus('Saving client settings…')", "setClientSettingsStatus('Saving…')", "client settings saving"),
    ("setClientSettingsStatus('Client settings saved.', 'ok');\n      toast('clientSettingsSaved');", "setClientSettingsStatus('Saved.', 'ok');", "client settings duplicate feedback"),
    ("err.message || 'Could not save client settings.'", "err.message || 'Could not save settings.'", "client settings save error"),
    ("n.custom_sound_name || 'No Custom Sound Uploaded'", "n.custom_sound_name || 'None uploaded'", "custom sound fallback"),
    ("status.textContent='Enable browser notifications or completion sound before testing.'", "status.textContent='Enable browser notifications or sound first.'", "notification test disabled"),
    ("status.textContent='Testing notification…'", "status.textContent='Testing…'", "notification test progress"),
    ("body:'This is a test notification from Torrent Dashboard.'", "body:'Test notification from Torrent Dashboard.'", "test notification body"),
    ("if (status) { status.className='test-result ok'; status.textContent=`Test successful: ${tested.join(' and ')}.`; }", "if (status) { status.className='test-result ok'; status.textContent='Test successful.'; }", "notification test success"),
    ("<div class=\"settings-empty\"><b>No Integrations Added</b><span>Choose an integration type above to add the first connection.</span></div>", "<div class=\"settings-empty\"><b>No integrations</b><span>Choose a type above to add one.</span></div>", "integration empty state"),
    ("<button class=\"secondary integration-test\" type=\"button\">Test Connection</button>", "<button class=\"secondary integration-test\" type=\"button\">Test</button>", "integration test label"),
    ("<div class=\"test-result muted integration-result\">Not Tested Yet</div>", "<div class=\"test-result muted integration-result\"></div>", "integration initial status"),
    ("'<option value=\"\">Choose Integration…</option>'", "'<option value=\"\">Choose integration…</option>'", "integration chooser"),
    ("return toast('Choose An Integration Type','error')", "return toast('Choose an integration type.','error')", "integration chooser error"),
    ("out.textContent='Testing Connection…'", "out.textContent='Testing…'", "integration progress"),
    ("<div class=\"settings-empty\"><b>No Users Found</b><span>Add an administrator account to manage Torrent Dashboard.</span></div>", "<div class=\"settings-empty\"><b>No users</b><span>Add an administrator to manage Torrent Dashboard.</span></div>", "users empty state"),
    ("<span class=\"field-label\">User Group <span class=\"required-mark\"", "<span class=\"field-label\">Role <span class=\"required-mark\"", "user role label"),
    ("return toast('Enter A Username','error')", "return toast('Enter a username.','error')", "username error"),
    ("return toast('Passwords Do Not Match','error')", "return toast('Passwords do not match.','error')", "password mismatch"),
]
for old, new, label in settings_replacements:
    settings_js = replace_once(settings_js, old, new, label)
settings_js = settings_js.replace("      const tested=[];\n", "")
settings_js = settings_js.replace("        tested.push('browser notification');\n", "")
settings_js = settings_js.replace("      if (soundEnabled) { await playSoundUrl(soundUrl); tested.push('completion sound'); }", "      if (soundEnabled) await playSoundUrl(soundUrl);")
old_delete_integration = "  async function deleteIntegration(card, item) {\n    if (!confirm(`Delete ${integrationLabel(item)}?`)) return;"
new_delete_integration = "  async function deleteIntegration(card, item) {\n    const confirmed = await showActionDialog({input:false,title:'Delete integration',message:`Delete “${integrationLabel(item)}”?`,confirmLabel:'Delete',danger:true});\n    if (!confirmed) return;"
settings_js = replace_once(settings_js, old_delete_integration, new_delete_integration, "integration delete dialog")
old_delete_user = "    if (!confirm(`Delete user ${user.username}?`)) return;"
new_delete_user = "    const confirmed=await showActionDialog({input:false,title:'Delete user',message:`Delete “${user.username}”?`,confirmLabel:'Delete',danger:true});\n    if (!confirmed) return;"
settings_js = replace_once(settings_js, old_delete_user, new_delete_user, "user delete dialog")
write("static/settings.js", settings_js)

# Empty status containers should not render decorative boxes/dots.
app_css = read("static/app.css")
if ".test-result:empty{display:none}" not in app_css:
    app_css += "\n/* 0.5.33 concise status surfaces */\n.test-result:empty{display:none}\n"
write("static/app.css", app_css)

settings_css = read("static/settings.css")
if ".client-settings-status:empty{display:none}" not in settings_css:
    settings_css += "\n/* 0.5.33 concise client status surface */\n.client-settings-status:empty{display:none}\n"
write("static/settings.css", settings_css)

sw = read("static/sw.js")
sw = replace_once(sw, "torrent-dashboard-v0532", "torrent-dashboard-v0533", "service worker cache")
sw = sw.replace("?v=0.5.32", "?v=0.5.33")
write("static/sw.js", sw)

# Tighten release checks around the revised UI contract.
validator = read("release_tools/validate_ui_strings.py")
validator = replace_once(
    validator,
    "    assert not re.search(r'\\bconfirm\\s*\\(', app_js)\n",
    "    assert not re.search(r'\\bconfirm\\s*\\(', app_js)\n    assert not re.search(r'\\bconfirm\\s*\\(', settings_js)\n",
    "native confirm validator",
)
marker = '    print("UI string audit passed")\n'
block = '''    # 0.5.33 concise copy and cross-site UI consistency.\n    assert 'Test successful: ' not in settings_js and "status.textContent='Test successful.'" in settings_js\n    assert 'Not Tested Yet' not in html and 'Not Tested Yet' not in app_js and 'Not Tested Yet' not in settings_js\n    assert 'No Custom Sound Uploaded' not in html and 'No Custom Sound Uploaded' not in settings_js\n    assert 'None uploaded' in html and 'None uploaded' in settings_js\n    assert 'User Management' not in html\n    assert '＋ Add Server' not in html and '＋ Add Client' in html\n    assert 'Test Connection' not in settings_js\n    assert '<span class="field-label">Role <span class="required-mark"' in settings_js\n    assert '.test-result:empty{display:none}' in app_css\n    assert '.client-settings-status:empty{display:none}' in settings_css\n    assert 'id="removeModalTitle"' in html and "$('#removeModalTitle').textContent" in app_js\n    assert 'aria-label="Close details"' in html and 'aria-label="Close add torrent"' in html\n    for duplicate in ("toast('profileSaved')", "toast('passwordChanged')", "toast('profilePictureUpdated')", "toast('profilePictureRemoved')"):\n        assert duplicate not in app_js\n    assert "toast('clientSettingsSaved')" not in settings_js\n\n'''
validator = replace_once(validator, marker, block + marker, "0.5.33 validator block")
write("release_tools/validate_ui_strings.py", validator)

# Final staging assertions catch accidental partial replacement before CI validation.
final_html = read("static/index.html")
final_app = read("static/app.js")
final_settings = read("static/settings.js")
assert 'Test successful: ' not in final_settings
assert "status.textContent='Test successful.'" in final_settings
assert 'User Management' not in final_html
assert '＋ Add Client' in final_html
assert 'Not Tested Yet' not in final_html + final_app + final_settings
assert 'confirm(' not in final_settings
assert 'id="removeModalTitle"' in final_html
assert 'VERSION = "0.5.33"' in read("dashboard.py")

print("Applied 0.5.33 UI copy and consistency pass.")
