#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "release_notes" / "releases.json"


def version_key(value: str):
    raw = str(value or "").strip().lstrip("vV")
    if not re.fullmatch(r"\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?", raw):
        raise RuntimeError(f"Invalid semantic version in release metadata: {value}")
    main, sep, suffix = raw.partition("-")
    nums = tuple(int(part) for part in main.split("."))
    return (*nums, 1 if not sep else 0, suffix.lower())


def load_source():
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or not isinstance(data.get("releases"), list):
        raise RuntimeError("release_notes/releases.json must contain a releases array")
    seen = set()
    releases = []
    for raw in data["releases"]:
        if not isinstance(raw, dict):
            raise RuntimeError("Every release entry must be an object")
        version = str(raw.get("version") or "").strip().lstrip("vV")
        version_key(version)
        if version in seen:
            raise RuntimeError(f"Duplicate release metadata for v{version}")
        seen.add(version)
        summary = str(raw.get("summary") or "").strip()
        title = str(raw.get("title") or "").strip()
        if not summary or not title:
            raise RuntimeError(f"v{version} requires title and summary")
        item = dict(raw)
        item["version"] = version
        for field in ("highlights", "fixes", "technical", "validation", "known_issues", "architecture", "decisions"):
            value = item.get(field, [])
            if value is None:
                value = []
            if not isinstance(value, list) or not all(isinstance(x, str) and x.strip() for x in value):
                raise RuntimeError(f"v{version} field {field} must be a list of non-empty strings")
            item[field] = [x.strip() for x in value]
        next_steps = item.get("next_steps", []) or []
        if not isinstance(next_steps, list):
            raise RuntimeError(f"v{version} next_steps must be a list")
        normalized_steps = []
        for step in next_steps:
            if not isinstance(step, dict):
                raise RuntimeError(f"v{version} next_steps entries must be objects")
            priority = int(step.get("priority") or 0)
            title_text = str(step.get("title") or "").strip()
            detail = str(step.get("detail") or "").strip()
            if priority < 1 or not title_text or not detail:
                raise RuntimeError(f"v{version} next_steps entries require priority, title, and detail")
            normalized_steps.append({"priority": priority, "title": title_text, "detail": detail})
        item["next_steps"] = sorted(normalized_steps, key=lambda x: x["priority"])
        releases.append(item)
    releases.sort(key=lambda x: version_key(x["version"]), reverse=True)
    project = data.get("project") if isinstance(data.get("project"), dict) else {}
    return project, releases


def bullets(items):
    return "\n".join(f"- {item}" for item in items)


def render_release_body(item):
    lines = [f"## v{item['version']} — {item['title']}", "", item["summary"].strip()]
    sections = [
        ("What's changed", item["highlights"]),
        ("Fixes", item["fixes"]),
        ("Technical notes", item["technical"]),
        ("Validation", item["validation"]),
        ("Known issues", item["known_issues"]),
    ]
    for heading, values in sections:
        if values:
            lines.extend(["", f"### {heading}", "", bullets(values)])
    lines.append("")
    return "\n".join(lines)


def render_changelog(releases):
    lines = [
        "# Torrent Dashboard Changelog",
        "",
        "> Generated from `release_notes/releases.json`. Do not edit this file manually.",
        "",
    ]
    for item in releases:
        lines.extend([render_release_body(item).rstrip(), ""])
    return "\n".join(lines).rstrip() + "\n"


def render_project_state(project, releases):
    latest = releases[0]
    lines = [
        "# Torrent Dashboard Project State",
        "",
        "> Generated from `release_notes/releases.json`. Do not edit this file manually.",
        "",
        "## Current baseline",
        "",
        f"- Latest documented build: **v{latest['version']}** ({latest.get('status', 'unknown')})",
        f"- Repository: `{project.get('repository', 'CynicaGaming/TorrentDashboard')}`",
        f"- Development branch: `{project.get('development_branch', '')}`",
        f"- Prerelease branch: `{project.get('prerelease_branch', '')}`",
    ]
    if project.get("pull_request"):
        lines.append(f"- Active refactor PR: **#{project['pull_request']}**")
    lines.extend(["", "### Latest release summary", "", latest["summary"]])

    if latest.get("architecture"):
        lines.extend(["", "## Architecture state", "", bullets(latest["architecture"])])
    if latest.get("decisions"):
        lines.extend(["", "## Current engineering decisions", "", bullets(latest["decisions"])])
    if project.get("principles"):
        lines.extend(["", "## Development principles", "", bullets([str(x).strip() for x in project["principles"] if str(x).strip()])])

    lines.extend(["", "## Recent work", ""])
    for item in releases[:5]:
        lines.extend([f"### v{item['version']} — {item['title']}", "", item["summary"], ""])
        if item["highlights"]:
            lines.extend([bullets(item["highlights"]), ""])

    lines.extend(["## What to do next", ""])
    if latest.get("next_steps"):
        for step in latest["next_steps"]:
            lines.extend([f"{step['priority']}. **{step['title']}** — {step['detail']}"])
    else:
        lines.append("No next steps are recorded in the latest release metadata.")

    if latest.get("known_issues"):
        lines.extend(["", "## Known issues", "", bullets(latest["known_issues"])])

    lines.extend([
        "",
        "## Handoff instructions for a new development session",
        "",
        "1. Read this file first.",
        "2. Review the latest entry in `release_notes/releases.json` for the structured source data.",
        "3. Inspect the development branch and active pull request before making changes.",
        "4. Continue from **What to do next** unless the project owner changes priorities.",
        "5. For every completed prerelease increment, add or update structured release metadata and regenerate this file and `CHANGELOG.md`.",
        "",
    ])
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool):
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            raise RuntimeError(f"Generated file is stale: {path.relative_to(ROOT)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Generate Torrent Dashboard release and handoff notes")
    parser.add_argument("--version", required=True)
    parser.add_argument("--release-body")
    parser.add_argument("--project-state", default="PROJECT_STATE.md")
    parser.add_argument("--changelog", default="CHANGELOG.md")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    project, releases = load_source()
    wanted = str(args.version).strip().lstrip("vV")
    release = next((item for item in releases if item["version"] == wanted), None)
    if not release:
        raise RuntimeError(f"No release metadata exists for v{wanted}")

    project_state = render_project_state(project, releases)
    changelog = render_changelog(releases)
    write_or_check(ROOT / args.project_state, project_state, args.check)
    write_or_check(ROOT / args.changelog, changelog, args.check)

    if args.release_body:
        path = ROOT / args.release_body
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render_release_body(release), encoding="utf-8")

    print(f"Release metadata OK for v{wanted}")


if __name__ == "__main__":
    main()
